# Generated by Django 6.0.7 on 2026-07-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='uploaded_resume.pdf', max_length=255)),
                ('ats_score', models.IntegerField(default=0)),
                ('rf_predicted_status', models.CharField(default='Shortlisted', max_length=50)),
                ('rf_confidence', models.FloatField(default=0.0)),
                ('word_count', models.IntegerField(default=0)),
                ('extracted_skills', models.TextField(blank=True, null=True)),
                ('suggested_jobs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedCompanyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField()),
                ('industry', models.CharField(default='Unknown Industry', max_length=150)),
                ('company_info', models.TextField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
